Components are function()'s
VITO-RMA/cra-template-vitotypescript pull request #1
Opened 2021-12-08 13:11 UTC by hoetmaaiers

2021-12-08 13:39 UTC, vump commented
Haha, different coding styles! Laten we voor een compromis gaan?
Componenten :
```
export function ComponentName(props:Props) {
   ...
}
```

Maar geen `render()` functies?
Ik vind dat dat aanmoedigt om meerdere render functies te maken in een component en dan vind ik dat je een subcomponent moet maken ipv een aparte render functie!

2021-12-08 13:41 UTC, vump requested changes
Haha, different coding styles! Laten we voor een compromis gaan?
Componenten :
```
export function ComponentName(props:Props) {
   ...
}
```
Maar geen `render()` functies?
Ik vind dat dat aanmoedigt om meerdere render functies te maken in een component en dan vind ik dat je een subcomponent moet maken ipv een aparte render functie!

2021-12-08 14:00 UTC, hoetmaaiers commented
In de ideale wereld is het direct duidelijk dat een return ook je component return is. Ik merk dat een iets uitgebreider component langer wordt dan mijn schermhoogte en ik dus moet turen of dit de return is van een functie, een memo of van component zelf.

Dat is waarom ik dat doe, maar ik kan met het compromis leven in de template hoeft het er niet bij.

2021-12-09 13:00 UTC, vump approved these changes

2021-12-09 13:01 UTC, merged